version: '3.8'

services:
  web:
    build: ./docker
    command: python ./django_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://testautomation:password@db:5432/testautomation

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=testautomation
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testautomation

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  selenium-node-chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

volumes:
  postgres_data:
